### ISSUE TITLE
Finish spectral analysis code

### ISSUE THREAD

**Issue by ceriottm** [epfl-cosmo/gle4md#2]
Code to compute GLE spectral analysis has been added, but all the wirings to gle-fit and gle-analyze have to be remade.

**Comment by mahrossi** [comment]
Are the fittings in gle-analyze only into gle-analyze.cpp? I'm onto it.

**Comment by ceriottm** [comment]
Well, one needs to include new optimization targets in libglefit.cpp and in
glefit.hpp, both for the spectral disturbance to the actual single
frequency case (harm_check, we could call them
wspecq, sspecq, ispecq, wspecp, sspecp, ispecp) and for rp_check
(rp_wspecq, rp_sspecq, .... ) Furthermore one should also add for
harm_check the "main peak indicators", that is re, im , resq, resp for the
main pole.
Thanks!

**Comment by mahrossi** [comment]
yes yes i called them differently but i think i finished
