### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sasuke-git** [epfl-cosmo/gle4md#6]
When compiling with make, it prompts that tbdefs.hpp is missing?
looking forward to a reply!!
![image](https://github.com/lab-cosmo/gle4md/assets/73691645/488344e3-2caf-41a9-aa2f-64c3d76358f8)

**Comment by ceriottm** [comment]
I added some compilation instructions to the README file. See if they work for you, otherwise I'll go back and tweak those, so it can also help others in the future.

**Comment by sasuke-git** [comment]
> I added some compilation instructions to the README file. See if they work for you, otherwise I'll go back and tweak those, so it can also help others in the future.

After running `make` in the `toolbox/src` directory, I encountered a new error. Could this be an issue with my GCC version?
![image](https://github.com/lab-cosmo/gle4md/assets/73691645/dc65a7f9-6a58-4c7a-8bf6-7739e1b11824)

**Comment by ceriottm** [comment]
no it needs libboost-regex to use regular expressions, but that's optional. pull again on the toolbox repo, I changed the default so it's easier to compile as a library. can you try again?

**Comment by sasuke-git** [comment]
> no it needs libboost-regex to use regular expressions, but that's optional. pull again on the toolbox repo, I changed the default so it's easier to compile as a library. can you try again?

Oh, yes, this time it installed successfully! Thank you so much!
