### ISSUE TITLE
Parameter settings in the kw-fit.in file

### ISSUE THREAD

**Issue by sasuke-git** [epfl-cosmo/gle4md#7]
OK, I'm back again, and I really need your help！^ ^
I've noticed that the parameters at the beginning of the kw-fit.in file need to be preset as shown in the following image, but I'm currently unclear about the specific meanings of some of these parameters. Do you have any suggestions for these parameters, or are they related to some physical quantities of the system I am simulating? In the points section, I have placed a target Kw kernel function, with w in units of PHz. I aim to obtain an A matrix to use in LAMMPS, and I would prefer that the elements of the A matrix are in units of PHz (i.e., the reciprocal of a femtosecond) because the time unit in LAMMPS when using real units is femtoseconds. Additionally, my simulation temperature is 400K.
![image](https://github.com/lab-cosmo/gle4md/assets/73691645/2c8f24f6-682b-4973-845d-1d77028a4edb)

**Comment by ceriottm** [comment]
Hello. I am sorry, but as the README says, this package is poorly documented and not maintained. You can look at the code to get some ideas of what these do, and read sec. 2.3 in [this thesis](http://e-collection.ethbib.ethz.ch/eserv/eth:2145/eth-2145-02.pdf) to get an idea of the theory. However, if you just want to use a thermostat for a "usual" purpose (e.g. being efficient at sampling in molecular dynamics) your best bet is using the [simplified generator](https://gle4md.org/index.html?page=matrix) that has many pre-fitted matrices that are adapted to your system based on easy-to-understand parameters.

**Comment by sasuke-git** [comment]
> Hello. I am sorry, but as the README says, this package is poorly documented and not maintained. You can look at the code to get some ideas of what these do, and read sec. 2.3 in [this thesis](http://e-collection.ethbib.ethz.ch/eserv/eth:2145/eth-2145-02.pdf) to get an idea of the theory. However, if you just want to use a thermostat for a "usual" purpose (e.g. being efficient at sampling in molecular dynamics) your best bet is using the [simplified generator](https://gle4md.org/index.html?page=matrix) that has many pre-fitted matrices that are adapted to your system based on easy-to-understand parameters.

OK,Thanks!
